name: test suite
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v30
      - name: Build Elvish with all packages
        run: |
          nix build '.#elvish-with-all-packages'
      - name: Run tests
        run: |
          ./result/bin/elvish tests/use-all.elv
